robot:
  id: dsr01
  model: m0609
  node_name: coverage_path
  frames:
    tf_source: base_link
    tf_target: link_6
  reach_m: 0.9
  init_posx:
    # - -142.39569091796875
    # - 555.5761108398438
    # - 369.9364318847656
    # - 81.62047576904297
    # - 180.0
    # - 156.6204833984375
    - -108.639
    - 452.699
    - 501.480
    - 104.69
    - 142.73
    - 1.77
  all_zero_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

motion_backend: moveit

camera:
  image_topic: /camera/camera/color/image_raw/compressed
  rgb_topic: /camera/camera/color/image_raw
  depth_topic: /camera/camera/aligned_depth_to_color/image_raw
  depth_unit: auto
  intrinsics:
    fx: 611.9779052734375
    fy: 611.1830444335938
    cx: 315.73968505859375
    cy: 232.30418395996094

transforms:
  world_to_base:
    euler_xyz: [0.0, 0.0, 3.141519]
    degrees: false
    translation: [-0.61, 0.365, 0.91]
  link_to_camera:
    # quaternion_xyzw: [0.0048, -0.7017, 0.7124, -0.0047]
    # translation: [-0.0429, 0.0389, 0.0950]
    quaternion_xyzw: [0.0069, -0.6980, 0.7160, -0.0045]
    translation: [-0.0336, 0.0378, 0.1082]
  gazebo_to_optical:
    matrix:
      # - [0.0, 0.0, 1.0]
      # - [-1.0, 0.0, 0.0]
      # - [0.0, -1.0, 0.0]
      - [0.0, -1.0, 0.0]
      - [0.0, 0.0, -1.0]
      - [1.0, 0.0, 0.0]
    translation: [0.0, 0.0, 0.0]

mesh:
  path: meshes/VMC-300-l.obj
  dimension: 1000.0
  world_to_cnc: [0.0, 0.0, 0.0]
  normal_query_radius: 10.
  velocity_scaling: 0.2
  acceleration_scaling: 0.2
  collision_object_id: cnc_mesh_obstacl0
  normal_sample_count: 5000000
  surface_offset_m: 0.2
  pose_mode: fixed_blower_z_axis # mesh_normal | fixed_blower_z_axis
  fixed_blower_z_axis:
    angle_from_world_y_deg: 45.0
    distance_m: 0.2

path_actions:
  cone_sweep:
    enabled: true
    angle_deg: 10.0
    samples: 8

moveit:
  group: manipulator
  base_frame: base_link
  ee_link: link_6
  joint_names: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
  joint_tolerance: 0.001
  planning_service: plan_kinematic_path
  move_action: move_action
  scene_service: apply_planning_scene
  scene_topic: planning_scene
  execute_action: execute_trajectory
  planning_time: 8.0
  planning_attempts: 10
  position_tolerance: 0.003
  orientation_tolerance: 0.05
  z_axis_only_orientation: true
  free_z_axis_tolerance: 3.14159
  yaw_optimization_deg: [0, 30, -30, 60, -60, 90, -90, 120, -120, 150, -150, 180]
  velocity_scaling: 0.2
  acceleration_scaling: 0.2
  collision_object_id: cnc_mesh_obstacl
  allow_cnc_collision_links: []
  collision_margin_m: 0.05
  disabled_self_collision_pairs:
    - [base_link, link_1]
    - [base_link, link_3]
    - [link_1, link_2]
    - [link_1, link_3]
    - [link_1, link_5]
    - [link_1, link_6]
    - [link_2, link_3]
    - [link_2, link_4]
    - [link_2, link_5]
    - [link_2, link_6]
    - [link_3, link_4]
    - [link_3, link_5]
    - [link_3, link_6]
    - [link_4, link_5]
    - [link_4, link_6]
    - [link_5, link_6"]
    - [blower_link, link_6]

visualization:
  show_normals: true
  show_trajectory: true
  show_debug_scene: true
  trajectory_axis_len: 0.2

point_input:
  use_interactive_picker_when_query_pixels_empty: true

chip_detector:
  # enabled: true
  enabled: false 
  frames_to_average: 30
  frame_timeout_sec: 10.0
  reference_timeout_sec: 15.0
  current_timeout_sec: 15.0
  min_valid_mm: 10.0
  thresh_min_mm: 1.0
  thresh_max_mm: 50.0
  kmax: 3
  random_state: 0
  resample_cap: 1000
  depth_fit_scale: 0.5
  depth_pdf_downsample_factor: 2
  rgb_fit_scale: 0.5
  rgb_num_features: 500
  rgb_sift_contrast: 0.06
  rgb_sift_edge: 6
  rgb_n_components: 5
  rgb_include_outliers: true
  rgb_outlier_radius: 15
  rgb_outlier_probability: 0.8
  rgb_pdf_downsample_factor: 2
  depth_weight: 0.5
  rgb_weight: 0.5
  sample_count: 5
  sample_random_seed: 0
  show_pdf_overlay: true
  pdf_overlay_alpha: 0.55
  mask_roi:
    x_min: 200
    x_max: -1
    y_min: 200
    y_max: 550

execution:
  execute_gazebo_first: true
  confirm_real_execution: true
  online_segment_settle_sec: 0.2
